version: '2'

networks:
  gallifrey:
    external: true

services:
  django:
    build: .
    user: django
    ports:
      - "5000"
    command: /start.sh
    env_file: .env
    networks:
      - gallifrey
